INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('john', 'tomas2', 'test@test.com');

select *
from CUSTOMERS;


CREATE TABLE C##CDC.ORDERS
(
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID NUMBER        NOT NULL,
    AMOUNT      NUMBER(12, 2) NOT NULL,
    UPDATED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

ALTER TABLE C##CDC.ORDERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;


INSERT INTO ORDERS (CUSTOMER_ID, AMOUNT)
VALUES (1, 100);


-- Run this as C##CDC on XEPDB1 service, e.g.:
-- sqlplus C##CDC/cdcpass@//localhost:1521/XEPDB1

-- =========
-- INSERTS
-- =========
INSERT INTO C##CDC.CUSTOMERS (first_name, last_name, email) VALUES ('Alice', 'Anderson', 'alice.anderson@example.com');
INSERT INTO C##CDC.CUSTOMERS (first_name, last_name, email) VALUES ('Bob', 'Baker', 'bob.baker@example.com');
INSERT INTO C##CDC.CUSTOMERS (first_name, last_name, email) VALUES ('Charlie', 'Clark', 'charlie.clark@example.com');

INSERT INTO C##CDC.PROJECTS (name) VALUES ('Project A');
INSERT INTO C##CDC.PROJECTS (name) VALUES ('Project B');

INSERT INTO C##CDC.EMPLOYEES (name) VALUES ('John Smith');
INSERT INTO C##CDC.EMPLOYEES (name) VALUES ('Mary Johnson');

INSERT INTO C##CDC.DEPARTMENTS (name) VALUES ('Sales');
INSERT INTO C##CDC.DEPARTMENTS (name) VALUES ('Engineering');

INSERT INTO C##CDC.PRODUCTS (name) VALUES ('Widget');
INSERT INTO C##CDC.PRODUCTS (name) VALUES ('Gadget');

INSERT INTO C##CDC.ORDERS_SIMPLE (name) VALUES ('Order-001');
INSERT INTO C##CDC.ORDERS_SIMPLE (name) VALUES ('Order-002');

COMMIT;

-- =========
-- UPDATES
-- =========
UPDATE C##CDC.CUSTOMERS
SET email = 'alice.updated@example.com'
WHERE first_name = 'Alice' AND last_name = 'Anderson';

UPDATE C##CDC.PROJECTS
SET name = name || ' v2'
WHERE name = 'Project A';

UPDATE C##CDC.EMPLOYEES
SET name = 'John Smith Jr.'
WHERE name = 'John Smith';

UPDATE C##CDC.DEPARTMENTS
SET name = 'Sales & Marketing'
WHERE name = 'Sales';

UPDATE C##CDC.PRODUCTS
SET name = 'Widget Pro'
WHERE name = 'Widget';

UPDATE C##CDC.ORDERS_SIMPLE
SET name = 'Order-001-UPDATED'
WHERE name = 'Order-001';

COMMIT;

-- =========
-- DELETES
-- =========
DELETE FROM C##CDC.CUSTOMERS
WHERE first_name = 'Bob' AND last_name = 'Baker';

DELETE FROM C##CDC.PROJECTS
WHERE name = 'Project B';

DELETE FROM C##CDC.EMPLOYEES
WHERE name = 'Mary Johnson';

DELETE FROM C##CDC.DEPARTMENTS
WHERE name = 'Engineering';

DELETE FROM C##CDC.PRODUCTS
WHERE name = 'Gadget';

DELETE FROM C##CDC.ORDERS_SIMPLE
WHERE name = 'Order-002';

COMMIT;

-- =========
-- OPTIONAL: quick visibility checks
-- =========
SELECT COUNT(*) AS customers_cnt FROM C##CDC.CUSTOMERS;
SELECT COUNT(*) AS projects_cnt  FROM C##CDC.PROJECTS;
SELECT COUNT(*) AS employees_cnt FROM C##CDC.EMPLOYEES;
SELECT COUNT(*) AS departments_cnt FROM C##CDC.DEPARTMENTS;
SELECT COUNT(*) AS products_cnt FROM C##CDC.PRODUCTS;
SELECT COUNT(*) AS orders_cnt FROM C##CDC.ORDERS_SIMPLE;